import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import time
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_groq import ChatGroq
from langchain.agents import create_agent

st.set_page_config(page_title="AI Powered Data Analyst Agent", layout="wide")

st.title("🤖 AI-Powered Data Analyst Agent")
st.write("Upload your dataset or use the default Superstore dataset to automatically perform EDA, generate univariate, bivariate, and multivariate visualizations, and chat with your data.")

# Sidebar for API Keys and File Upload
st.sidebar.header("Configuration & Upload")
GOOGLE_API_KEY = st.sidebar.text_input("Google API Key", type="password")
GROQ_API_KEY = st.sidebar.text_input("Groq API Key", type="password")

uploaded_file = st.sidebar.file_uploader("Upload CSV or Excel file", type=["csv", "xlsx", "xls"])

use_default = st.sidebar.checkbox("Use Default Superstore Dataset", value=True)

# Model initialization function
@st.cache_resource
def init_models(g_key, gr_key):
    if not g_key or not gr_key:
        return None, None
    gemini = ChatGoogleGenerativeAI(
        model="gemini-1.5-flash",
        google_api_key=g_key
    )
    groq = ChatGroq(
        model="qwen-2.5-coder-32b",
        api_key=gr_key
    )
    return gemini, groq

gemini_llm, groq_llm = init_models(GOOGLE_API_KEY, GROQ_API_KEY)

def temp_tool():
    """This is just a dummy tool"""
    return "Hello world"

# Determine data source
if use_default:
    file_path = 'https://raw.githubusercontent.com/axisgras-hash/DATASETS/refs/heads/main/Superstore.csv'
elif uploaded_file is not None:
    if uploaded_file.name.endswith('.csv'):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)
    file_path = uploaded_file
else:
    file_path = None

if file_path and isinstance(file_path, str):
    try:
        df = pd.read_csv(file_path)
    except Exception as e:
        st.error(f"Error loading file: {e}")

if 'df' in locals() and df is not None:
    st.success("Dataset Loaded Successfully!")
    st.dataframe(df.head())

    if gemini_llm:
        agent = create_agent(
            model=gemini_llm,
            tools=[temp_tool]
        )

        if st.button("Run AI Automated EDA & Charts"):
            with st.spinner("AI is analyzing the dataset and writing python code for visualization..."):
                try:
                    sample_df = df.sample(min(5, len(df)))
                    prompt = f"""You are a data analyst. Perform basic EDA and generate python code 
                    that returns statistical insights, missing values, shape, size for dataframe sample: {sample_df}"""
                    
                    response = agent.invoke({'messages': [{'role': 'user', 'content': prompt}]})
                    ans = response["messages"][-1].content
                    if isinstance(ans, list):
                        ans = ans[-1].get('text', str(ans))
                    
                    # Extract code block safely
                    if "```python" in ans:
                        code = ans.split("```python")[1].split("```")[0]
                    elif "```" in ans:
                        code = ans.split("```")[1].split("```")[0]
                    else:
                        code = ans

                    st.subheader("Basic EDA Code Generated by Agent:")
                    st.code(code, language='python')

                    # Advanced EDA Prompt Generation
                    advance_prompt = """Give detailed Python code for advanced data analysis including describe, 
                    correlation matrix, univariate numerical and categorical column analysis, bivariate analysis, 
                    and multivariate analysis using matplotlib/seaborn plots. Assume df is already loaded."""
                    
                    adv_response = agent.invoke({'messages': [{'role': 'user', 'content': advance_prompt}]})
                    adv_ans = adv_response["messages"][-1].content
                    if isinstance(adv_ans, list):
                        adv_ans = adv_ans[-1].get('text', str(adv_ans))
                    
                    if "```python" in adv_ans:
                        adv_code = adv_ans.split("```python")[1].split("```")[0]
                    elif "```" in adv_ans:
                        adv_code = adv_ans.split("```")[1].split("```")[0]
                    else:
                        adv_code = adv_ans

                    st.subheader("Advanced EDA & Visualization Code:")
                    st.code(adv_code, language='python')

                    st.subheader("Executing Generated Analysis & Charts:")
                    # Execute advanced analysis dynamically with df in local scope
                    local_vars = {'df': df, 'plt': plt, 'sns': sns, 'pd': pd, 'np': np}
                    try:
                        exec(adv_code, {}, local_vars)
                        for plt_num in plt.get_fignums():
                            st.pyplot(plt.figure(plt_num))
                    except Exception as exec_err:
                        st.warning(f"Dynamic code execution had minor issues, rendering default analysis instead: {exec_err}")
                        
                        # Fallback default visualizations for robust user experience
                        st.write("### Univariate Analysis (Numerical Distributions)")
                        num_cols = df.select_dtypes(include=[np.number]).columns[:3]
                        for col in num_cols:
                            fig, ax = plt.subplots(figsize=(8, 4))
                            sns.histplot(df[col].dropna(), kde=True, ax=ax)
                            ax.set_title(f'Distribution of {col}')
                            st.pyplot(fig)

                        st.write("### Bivariate Analysis (Correlation Heatmap)")
                        if len(num_cols) > 1:
                            fig, ax = plt.subplots(figsize=(8, 6))
                            sns.heatmap(df[num_cols].corr(), annot=True, cmap='coolwarm', ax=ax)
                            ax.set_title('Correlation Matrix')
                            st.pyplot(fig)

                except Exception as e:
                    st.error(f"Agent execution error: {e}")
    else:
        st.info("Please enter your Google API Key and Groq API Key in the sidebar to enable AI Analysis and Chat features.")

    # Chat with Data Feature
    st.divider()
    st.subheader("💬 Chat with your Dataset")
    user_query = st.text_input("Ask anything about your dataset (e.g., 'What is total sales by region?'):")
    if user_query and gemini_llm:
        with st.spinner("AI is thinking..."):
            chat_prompt = f"""You are an expert data analyst assistant. 
            Here is the dataframe info:
            Columns: {list(df.columns)}
            Sample Data: {df.head(3).to_dict()}
            
            Answer this user question professionally and accurately based on the dataset context: {user_query}"""
            
            chat_response = gemini_llm.invoke(chat_prompt)
            st.write(chat_response.content)
else:
    st.warning("Please upload a dataset or enable the default dataset to proceed.")